### ISSUE TITLE
[agenda]: Technical community call July 2024

### ISSUE THREAD

**Issue by bguiz** [hedera-dev/hedera-comm-calls#2]
### Meeting Details

* Date: TODO [20240725T000000Z](https://www.timeanddate.com/worldclock/converter.html?iso=20240725T000000&p1=1440&p2=137&p3=179&p4=136&p5=37&p6=776&p7=176&p8=236&p9=240)
* Stream: 

### What type of call is this?

Technical

### Topics

* HIP-1234: Placeholder HIP title
  * (nil) --> Review
  * https://hips.hedera.com/hip/hip-1234
* Topic without a HIP 1

### TODOs

- [ ] Create notes file + update table in main README
- [ ] URLs + QR codes for discord/ youtube/ twitter streams
- [ ] Tweet storm first post URL + QR code
- [ ] Full bio details for each of the speakers
  - [ ] Name/ nickname
  - [ ] Company
  - [ ] Twitter/ LinkedIn/ Website
  - [ ] Intro bullet points
- [ ] Identify dev community members for shout outs
- [ ] Prepare slide deck
- [ ] Slides for each of the presenters
- [ ] Announcement tweets
- [ ] Update notes file + update table in main README
